name: 🤖 Auto-Reply to Issues

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  auto-comment:
    runs-on: ubuntu-latest

    steps:
    - name: Comment on new issue
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const issueNumber = context.issue.number;
          const username = context.payload.issue.user.login;
          const comment = [
            `👋 Hello @${username}, thanks for opening an issue!`,
            ``,
            `Before we dive in, check out our [README](https://github.com/ModuleMaster64/PythonProgramsV3#readme) and see if your question is covered.`,
            ``,
            `We appreciate your input — stay calm and collected! Have a great day`
          ].join('\n');

          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issueNumber,
            body: comment
          });
