name: 🤖 Auto-Reply to Issues

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  auto-comment:
    runs-on: ubuntu-latest

    steps:
    - name: Comment on new issue
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const issueNumber = context.issue.number;
          const username = context.payload.issue.user.login;
          const comment = [
            `👋 Hello @${username}, thank you for opening an issue!`,
            ``,
            `I will get back to you as soon as i can. - MM64`,
            ``,
            `We appreciate your input — Have a great day!`
          ].join('\n');

          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issueNumber,
            body: comment
          });
