name: 🧠 Daily Python Tip

on:
  schedule:
    - cron: '0 9 * * *'  # Every day at 9 AM BST

jobs:
  post-tip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Pick a random tip
      id: tip
      run: |
        TIP=$(shuf -n 1 tips.txt)
        echo "TIP=$TIP" >> $GITHUB_ENV

    - name: Post to Discussions
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const title = `🐍 Daily Python Tip – ${new Date().toISOString().split('T')[0]}`;
          const body = process.env.TIP;
          await github.rest.discussions.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            category_id: 'Daily Python Tips',
            title: title,
            body: body
          });
