name: README Beautifier 🇬🇧

on:
  push:
    paths:
      - README.md

jobs:
  beautify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Beautify README
        run: |
          # Create temp file
          cp README.md temp.md

          # Add badges if missing
          grep -q "Build Status" temp.md || echo "![Build Status](https://img.shields.io/badge/build-passing-brightgreen)" > temp.md
          grep -q "Banter Level" temp.md || echo "![Banter Level](https://img.shields.io/badge/banter-legendary-blue)" >> temp.md

          # Emoji-ify headers
          sed -i 's/^# /# 🚀 /' temp.md
          sed -i 's/^## /## 📦 /' temp.md
          sed -i 's/^### /### 🔧 /' temp.md

          # Add random British quote
          quotes=(
            "Keep calm and carry on."
            "Bob’s your uncle."
            "Fancy a cuppa?"
            "Mind the gap."
            "It’s not rocket science, innit?"
            "Bit of a faff, but we got there."
            "Sorted like a proper legend."
            "Cheeky bit of code, that."
            "All done and dusted."
            "Lovely jubbly."
          )
          RANDOM_INDEX=$((RANDOM % ${#quotes[@]}))
          echo -e "\n---\n🇬🇧 _\"${quotes[$RANDOM_INDEX]}\"_" >> temp.md

          mv temp.md README.md

      - name: Commit and Push
        env:
          GH_TOKEN: ${{ secrets.GH_BANTER_TOKEN }}
        run: |
          git config user.name "README Beautifier Bot"
          git config user.email "beautifier@example.com"
          git add README.md
          git commit -m "🧼 Beautified README with badges, emojis, and British charm"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} HEAD:main
